#!/usr/bin/env python3
"""Optional real-weight / synthetic-activation EXL3 component probe.

Requires a locally installed, trusted ExLlamaV3 with the MUL1 interface read in
PF-S03, PyTorch/CUDA, safetensors and a subset audit generated by this kit.
It does NOT install code, rent a machine, download weights, change drivers,
qualify the whole model, or turn a component timing into a model throughput.
"""
from __future__ import annotations
import argparse
import gc
import hashlib
import inspect
import json
import math
import os
from pathlib import Path
import sys
import time
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from strata_ds_lab.common import ContractError, read_json, safe_path
from strata_ds_lab.prefill.audit import audit_exl3
from strata_ds_lab.prefill.layout import bundle_layout, MiB


def sha_file(path):
    h=hashlib.sha256()
    with open(path,'rb') as f:
        for block in iter(lambda:f.read(1<<20),b''):h.update(block)
    return h.hexdigest()


def main(argv=None):
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--checkpoint',required=True)
    p.add_argument('--files-list',required=True,help='small explicit JSON shard list sufficient for selected complete bundles')
    p.add_argument('--layer',type=int,default=0);p.add_argument('--expert',type=int,default=0)
    p.add_argument('--expected-linear-source-sha256',required=True)
    p.add_argument('--rows',default='1,8,16,32,64,128,256')
    p.add_argument('--repeats',type=int,default=5)
    p.add_argument('--device',default='cuda:0')
    p.add_argument('--maximum-component-gpu-mib',type=int,default=1024)
    p.add_argument('--output',required=True)
    p.add_argument('--allow-local-gpu-component-run',action='store_true')
    a=p.parse_args(argv)
    if not a.allow_local_gpu_component_run:raise ContractError('explicit local GPU component execution flag required')
    if a.repeats<3 or a.repeats>50:raise ContractError('repeats must be 3..50')
    rows=sorted(set(int(x) for x in a.rows.split(',')))
    if not rows or rows[0]<1 or rows[-1]>2048:raise ContractError('bounded component rows must be 1..2048')
    if not 128<=a.maximum_component_gpu_mib<=4096:raise ContractError('component budget must be 128..4096 MiB')
    out=Path(a.output)
    if out.exists():raise ContractError('output exists: no overwrite')
    report={'status':'STARTED','evidence':'COMPONENT_PROBE','whole_model_loaded':False,
            'activation_source':'SYNTHETIC_RANDOM_NOT_CAPTURED_MODEL_ACTIVATIONS',
            'quantization_quality_qualified':False,'gpu_prefill_engine_qualified':False,'cases':[]}
    # Exclusive create keeps failures inspectable; output is not a success marker.
    with out.open('x',encoding='utf-8') as result_file:
        try:
            root=Path(a.checkpoint).resolve();names=read_json(a.files_list)
            audit=audit_exl3(root,names)
            matches=[b for b in audit['bundles'] if (b['layer'],b['expert'])==(a.layer,a.expert)]
            if len(matches)!=1:raise ContractError('selected complete expert not in audit')
            import torch
            from safetensors import safe_open
            from exllamav3.modules.quant.exl3 import LinearEXL3
            from exllamav3.ext import exllamav3_ext
            source=Path(inspect.getfile(LinearEXL3)).resolve()
            source_digest=sha_file(source)
            if source_digest!=a.expected_linear_source_sha256:
                raise ContractError('installed LinearEXL3 differs from independently reviewed source hash')
            if not torch.cuda.is_available():raise ContractError('CUDA unavailable')
            device=torch.device(a.device)
            if device.type!='cuda':raise ContractError('CUDA device required')
            torch.cuda.set_device(device);torch.set_num_threads(2)
            torch.manual_seed(20261004)
            tensors={};digests={};transfers=[]
            bundle=matches[0]
            # Read only each selected component. Real full-shard hashes are a separate gate.
            for item in bundle['components']:
                with safe_open(str(safe_path(root,item['file'])),framework='pt',device='cpu') as f:
                    tensor=f.get_tensor(item['name']).contiguous().clone()
                raw=tensor.reshape(-1).view(torch.uint8).numpy().tobytes()
                if len(raw)!=item['bytes']:raise ContractError('component changed after header audit')
                digests[item['name']]=hashlib.sha256(raw).hexdigest();del raw
                pinned=tensor.pin_memory()
                start,end=torch.cuda.Event(enable_timing=True),torch.cuda.Event(enable_timing=True)
                start.record();loaded=pinned.to(device,non_blocking=True);end.record();end.synchronize()
                transfers.append({'name':item['name'],'payload_bytes':item['bytes'],'cuda_event_ms':start.elapsed_time(end),
                                  'scope':'one cold allocation/copy sample; not steady-state PCIe qualification'})
                tensors[item['name'].split('.')[-2]+'.'+item['name'].split('.')[-1]]=loaded
                del tensor,pinned
            linears={}
            for projection in ('w1','w3','w2'):
                packed={k.split('.')[1]:v for k,v in tensors.items() if k.startswith(projection+'.')}
                # Upstream expects 0x83DCD12D marker; audit already read it; recheck selected tensor.
                if int(packed['mul1'].item()) & 0xffffffff != 0x83DCD12D:raise ContractError('MUL1 marker changed')
                layer=LinearEXL3(config=None,in_features=packed['suh'].numel(),out_features=packed['svh'].numel(),
                                 out_dtype=torch.float16,key='expert.'+projection,**packed)
                if not hasattr(exllamav3_ext,'reconstruct_had_slice'):layer._fused_reconstruct=False
                linears[projection]=layer
            def forward(x,w,reconstruct):
                opts={'reconstruct':True} if reconstruct else {}
                gate=linears['w1'].forward(x,opts).float().clamp(max=10.)
                up=linears['w3'].forward(x,opts).float().clamp(min=-10.,max=10.)
                # Match pinned PackedExpert ordering: route scaling BEFORE w2, FP16 handoff.
                z=(torch.nn.functional.silu(gate)*up*w.float()).half().contiguous()
                return linears['w2'].forward(z,opts)
            report.update({'linear_source':str(source),'linear_source_sha256':source_digest,
                           'extension_path':getattr(exllamav3_ext,'__file__',None),
                           'torch':torch.__version__,'cuda_runtime':torch.version.cuda,
                           'gpu':torch.cuda.get_device_name(device),'capability':torch.cuda.get_device_capability(device),
                           'bundle_descriptor_digest':audit['bundle_descriptor_digest'],'selected_component_sha256':digests,
                           'selected_bundle_payload_bytes':bundle['payload_bytes'],'initial_h2d_samples':transfers,
                           'shape':{'hidden':5120,'intermediate':2304},
                           'limit_note':'post-operation peak guard, not an allocator-enforced hard cap'})
            with torch.inference_mode():
                for n in rows:
                    x=(torch.randn((n,5120),device=device,dtype=torch.float16)*.05).contiguous()
                    w=torch.full((n,1),.25,device=device,dtype=torch.float32)
                    baseline=forward(x,w,False);candidate=forward(x,w,True)
                    if not torch.isfinite(baseline).all() or not torch.isfinite(candidate).all():raise ContractError('nonfinite component output')
                    delta=candidate.float()-baseline.float()
                    parity={'max_abs':delta.abs().max().item(),'relative_l2':(delta.norm()/baseline.float().norm().clamp_min(1e-30)).item(),
                            'bit_equal':torch.equal(candidate,baseline),'qualified_threshold':None}
                    del baseline,candidate,delta
                    for mode in (False,True):
                        for _ in range(2):del_output=forward(x,w,mode);del del_output
                    torch.cuda.synchronize()
                    timings=[]
                    for trial in range(a.repeats):
                        for mode in ((False,True) if trial%2==0 else (True,False)):
                            gc.collect();torch.cuda.synchronize();torch.cuda.reset_peak_memory_stats(device)
                            before=torch.cuda.memory_allocated(device);start,end=torch.cuda.Event(enable_timing=True),torch.cuda.Event(enable_timing=True)
                            wall=time.perf_counter();start.record();y=forward(x,w,mode);end.record();end.synchronize()
                            ms=(time.perf_counter()-wall)*1000
                            if not torch.isfinite(y).all():raise ContractError('nonfinite measured component output')
                            peak=torch.cuda.max_memory_allocated(device);reserved=torch.cuda.max_memory_reserved(device)
                            if peak>a.maximum_component_gpu_mib*MiB:raise ContractError('component peak exceeds explicit probe budget')
                            timings.append({'mode':'forced_reconstruct' if mode else 'upstream_default','trial':trial,
                                            'wall_ms':ms,'cuda_interval_ms':start.elapsed_time(end),'before_allocated_bytes':before,
                                            'peak_allocated_bytes':peak,'peak_reserved_bytes':reserved,
                                            'transient_allocated_bytes':max(0,peak-before)})
                            del y
                    report['cases'].append({'rows':n,'parity':parity,'timings':timings})
                    del x,w
            report['status']='COMPONENT_MEASURED_NOT_MODEL_QUALIFIED'
        except Exception as e:
            report['status']='FAILED';report['error']=repr(e)
            result_file.write(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n');result_file.flush()
            raise
        result_file.write(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
    return 0
if __name__=='__main__':raise SystemExit(main())
