# This target is independent of CUDA and the model pack.
add_library(strata_ds41_suffix STATIC src/ds41/suffix_drafter.cpp)
target_include_directories(strata_ds41_suffix PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_features(strata_ds41_suffix PUBLIC cxx_std_17)
if(STRATA_BUILD_TESTS)
  enable_testing()
  add_executable(ds41_suffix_drafter_test src/ds41/tests/suffix_drafter_test.cpp)
  target_link_libraries(ds41_suffix_drafter_test PRIVATE strata_ds41_suffix)
  add_test(NAME ds41_suffix_drafter_test COMMAND ds41_suffix_drafter_test)
  if(UNIX)
    add_executable(ds41_generate_suffix_mock_test src/ds41/tests/generate_suffix_mock_test.cpp)
    target_link_libraries(ds41_generate_suffix_mock_test PRIVATE strata_ds41_suffix)
    add_test(NAME ds41_generate_suffix_mock_test COMMAND ds41_generate_suffix_mock_test)
  endif()
endif()
